# Generated by Django 6.0.2 on 2026-03-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_dvje_credit_alter_dvje_debit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dv',
            name='current_step',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='dvarchived',
            name='reason_of_archive',
            field=models.TextField(blank=True, default='No reason of archive provided', null=True),
        ),
        migrations.AlterField(
            model_name='dvje',
            name='account_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dvparticulars',
            name='adjustment_ft',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='dvparticulars',
            name='adjustment_np',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='dvparticulars',
            name='adjustment_tf',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
