# Generated by Django 6.0.2 on 2026-03-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dv_current_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('admin', 'System Administrator'), ('accounting', 'Accounting'), ('budget', 'Budget'), ('treasurer', 'Treasurer'), ('bac_gso', 'BAC/GSO'), ('mayors_office', "Mayor's Office")], max_length=50),
        ),
    ]
