# Generated by Django 6.0.2 on 2026-03-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dvje',
            old_name='account_title',
            new_name='account_code',
        ),
        migrations.RemoveField(
            model_name='dvje',
            name='description',
        ),
        migrations.AddField(
            model_name='dvje',
            name='particulars',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
