# Generated by Django 6.0.2 on 2026-04-15 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_account_title_dvje_account_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dvparticulars',
            name='adjustment_ft',
        ),
        migrations.RemoveField(
            model_name='dvparticulars',
            name='adjustment_np',
        ),
        migrations.RemoveField(
            model_name='dvparticulars',
            name='adjustment_tf',
        ),
        migrations.RemoveField(
            model_name='dvparticulars',
            name='devolved_ft',
        ),
        migrations.RemoveField(
            model_name='dvparticulars',
            name='devolved_np',
        ),
        migrations.RemoveField(
            model_name='dvparticulars',
            name='devolved_tf',
        ),
        migrations.RemoveField(
            model_name='dvparticulars',
            name='organic_ft',
        ),
        migrations.RemoveField(
            model_name='dvparticulars',
            name='organic_np',
        ),
        migrations.RemoveField(
            model_name='dvparticulars',
            name='organic_tf',
        ),
        migrations.RemoveField(
            model_name='dvparticulars',
            name='vmsb_ft',
        ),
        migrations.RemoveField(
            model_name='dvparticulars',
            name='vmsb_np',
        ),
        migrations.RemoveField(
            model_name='dvparticulars',
            name='vmsb_tf',
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='DVParticularValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('np', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Net Pay')),
                ('ft', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='15th')),
                ('tf', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='31st')),
                ('particulars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_values', to='api.dvparticulars')),
            ],
            options={
                'db_table': 'dv_particular_values',
            },
        ),
    ]
