# Generated by Django 6.0.2 on 2026-04-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_dvparticulars_adjustment_ft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dv',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('disapproved', 'Disapproved'), ('completed', 'Completed'), ('archived', 'Archived')], default='pending', max_length=20),
        ),
    ]
