# Generated by Django 6.0.2 on 2026-04-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_dvcategory_remove_dvparticulars_adjustment_ft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvparticularvalue',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='DVCategory',
        ),
    ]
