# Generated by Django 6.0.4 on 2026-04-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_dv_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dv',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('disapproved', 'Disapproved'), ('completed', 'Completed'), ('archived', 'Archived')], default='pending', max_length=20),
        ),
    ]
