# Generated by Django on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_dv_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dv',
            name='current_step',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
