# Generated by Django 6.0.4 on 2026-04-25 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_dv_current_step_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='DVReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='api.dv')),
            ],
            options={
                'db_table': 'dv_report',
            },
        ),
    ]
