# Generated by Django 6.0.2 on 2026-04-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_dvreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='dv',
            name='advice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dv',
            name='dv_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dv',
            name='transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dv',
            name='transaction_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
