# Generated by Django 6.0.2 on 2026-04-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_dv_advice_date_dv_dv_date_dv_transaction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dv',
            name='dv_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
