# Generated by Django 6.0.4 on 2026-04-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_dv_dv_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvpayment',
            name='jev_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dvpayment',
            name='rec_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
