# Generated by Django 6.0.2 on 2026-04-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_dv_dv_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dv',
            name='office',
        ),
        migrations.AddField(
            model_name='dv',
            name='office_unit_project',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dv',
            name='position_office',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
