# Generated by Django 6.0.2 on 2026-04-30 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_dv_office_dv_office_unit_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dv',
            name='payee',
        ),
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=11, null=True)),
                ('dv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payees', to='api.dv')),
            ],
            options={
                'db_table': 'payee',
            },
        ),
    ]
