# Generated by Django 6.0.2 on 2026-04-30 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_dv_payee_payee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payee',
            name='dv',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payees', to='api.dv'),
        ),
    ]
