# Generated by Django 6.0.2 on 2026-05-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_payee_dv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dv',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
