# Generated by Django 6.0.2 on 2026-05-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_dv_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dv',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
