# Generated by Django 6.0.3 on 2026-05-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_dv_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeptHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('department', models.CharField(choices=[('admin', 'System Administrator'), ('accounting', 'Accounting'), ('budget', 'Budget'), ('treasurer', 'Treasurer'), ('bac_gso', 'BAC/GSO'), ('mayors_office', "Mayor's Office")], max_length=50)),
            ],
            options={
                'db_table': 'dept_head',
            },
        ),
    ]
