# Generated by Django 6.0.4 on 2026-05-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_depthead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depthead',
            name='department',
            field=models.CharField(choices=[('admin', 'System Administrator'), ('accounting', 'Accounting'), ('budget', 'Budget'), ('treasurer', 'Treasurer'), ('bac_gso', 'BAC/GSO'), ('municipal_admin', 'Municipal Administrator'), ('mayors_office', "Mayor's Office")], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('admin', 'System Administrator'), ('accounting', 'Accounting'), ('budget', 'Budget'), ('treasurer', 'Treasurer'), ('bac_gso', 'BAC/GSO'), ('municipal_admin', 'Municipal Administrator'), ('mayors_office', "Mayor's Office")], max_length=50),
        ),
    ]
