# Generated by Django 6.0.2 on 2026-03-21 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dv_no', models.CharField(max_length=100, unique=True)),
                ('tracking_no', models.CharField(max_length=100, unique=True)),
                ('payee', models.CharField(max_length=255)),
                ('office', models.CharField(max_length=255)),
                ('cafoa_no', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateField()),
                ('advice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('responsibility_center', models.CharField(blank=True, max_length=255, null=True)),
                ('fund_source', models.CharField(choices=[('GF', 'GF'), ('20% DF', '20% DF'), ('5% DRRM', '5% DRRM'), ('GAD', 'GAD'), ('RA7171', 'RA7171'), ('SEF', 'SEF'), ('TF', 'TF'), ('PHILHEALTH', 'PHILHEALTH'), ('CALAMITY', 'CALAMITY')], max_length=50)),
                ('tin', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('disapproved', 'Disapproved'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('current_step', models.IntegerField(default=1)),
                ('last_disapproved_step', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dv',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pass_hashed', models.CharField(max_length=255)),
                ('department', models.CharField(choices=[('accounting', 'Accounting'), ('budget', 'Budget'), ('treasurer', 'Treasurer'), ('bac_gso', 'BAC/GSO'), ('mayors_office', "Mayor's Office")], max_length=50)),
                ('status', models.CharField(default='active', max_length=20)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='DVArchived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_date', models.DateField(auto_now_add=True)),
                ('reason_of_archive', models.TextField()),
                ('dv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archive_info', to='api.dv')),
            ],
            options={
                'db_table': 'dv_archived',
            },
        ),
        migrations.CreateModel(
            name='DVJE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('dv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='api.dv')),
            ],
            options={
                'db_table': 'dv_je',
            },
        ),
        migrations.CreateModel(
            name='DVParticulars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('jev_no', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('organic_np', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('devolved_np', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('vmsb_np', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('adjustment_np', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('organic_ft', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('devolved_ft', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('vmsb_ft', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('adjustment_ft', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('organic_tf', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('devolved_tf', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('vmsb_tf', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('adjustment_tf', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('dv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='particulars', to='api.dv')),
            ],
            options={
                'db_table': 'dv_particulars',
            },
        ),
        migrations.CreateModel(
            name='DVPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mop', models.CharField(choices=[('CASH', 'Cash'), ('CHECK', 'Check'), ('OTHERS', 'Others')], max_length=20)),
                ('mop_specify', models.CharField(blank=True, max_length=255, null=True)),
                ('atm_no', models.CharField(blank=True, max_length=100, null=True)),
                ('bank', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('dv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.dv')),
            ],
            options={
                'db_table': 'dv_payment',
            },
        ),
        migrations.CreateModel(
            name='DVWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('resubmitted', 'Resubmitted'), ('approved', 'Approved'), ('disapproved', 'Disapproved'), ('archived', 'Archived')], max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('dv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='api.dv')),
                ('action_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_actions', to='api.user')),
            ],
            options={
                'db_table': 'dv_workflow',
                'ordering': ['action_date'],
            },
        ),
        migrations.AddField(
            model_name='dv',
            name='accounting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dvs', to='api.user'),
        ),
    ]
